TrackForm:

<TrackForm>:
    orientation: "vertical"
	destination: None
	my_map: map
			
    BoxLayout:
        height: "40dp"
        size_hint_y: None
        Button:
            size_hint_x: 25
            text: "Analizuj plik"
            on_press: root.open_file()	
			
    BoxLayout:
        orientation: 'vertical'
        MapView:
            lat: 0
            lon: 0
            zoom: 1
            id: map

	
	